/**
 * ARTIK Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ArtikCloud);
  }
}(this, function(expect, ArtikCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ArtikCloud.DevicePricingTier();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DevicePricingTier', function() {
    it('should create an instance of DevicePricingTier', function() {
      // uncomment below and update the code to test DevicePricingTier
      //var instane = new ArtikCloud.DevicePricingTier();
      //expect(instance).to.be.a(ArtikCloud.DevicePricingTier);
    });

    it('should have the property messageLimit (base name: "messageLimit")', function() {
      // uncomment below and update the code to test the property messageLimit
      //var instane = new ArtikCloud.DevicePricingTier();
      //expect(instance).to.be();
    });

    it('should have the property cost (base name: "cost")', function() {
      // uncomment below and update the code to test the property cost
      //var instane = new ArtikCloud.DevicePricingTier();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new ArtikCloud.DevicePricingTier();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new ArtikCloud.DevicePricingTier();
      //expect(instance).to.be();
    });

    it('should have the property active (base name: "active")', function() {
      // uncomment below and update the code to test the property active
      //var instane = new ArtikCloud.DevicePricingTier();
      //expect(instance).to.be();
    });

    it('should have the property interval (base name: "interval")', function() {
      // uncomment below and update the code to test the property interval
      //var instane = new ArtikCloud.DevicePricingTier();
      //expect(instance).to.be();
    });

    it('should have the property ptid (base name: "ptid")', function() {
      // uncomment below and update the code to test the property ptid
      //var instane = new ArtikCloud.DevicePricingTier();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new ArtikCloud.DevicePricingTier();
      //expect(instance).to.be();
    });

    it('should have the property billingInterval (base name: "billingInterval")', function() {
      // uncomment below and update the code to test the property billingInterval
      //var instane = new ArtikCloud.DevicePricingTier();
      //expect(instance).to.be();
    });

  });

}));
