/**
 * ARTIK Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ArtikCloud);
  }
}(this, function(expect, ArtikCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ArtikCloud.DeviceTypeInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DeviceTypeInfo', function() {
    it('should create an instance of DeviceTypeInfo', function() {
      // uncomment below and update the code to test DeviceTypeInfo
      //var instane = new ArtikCloud.DeviceTypeInfo();
      //expect(instance).to.be.a(ArtikCloud.DeviceTypeInfo);
    });

    it('should have the property devicePropertiesEnabled (base name: "devicePropertiesEnabled")', function() {
      // uncomment below and update the code to test the property devicePropertiesEnabled
      //var instane = new ArtikCloud.DeviceTypeInfo();
      //expect(instance).to.be();
    });

    it('should have the property pmax (base name: "pmax")', function() {
      // uncomment below and update the code to test the property pmax
      //var instane = new ArtikCloud.DeviceTypeInfo();
      //expect(instance).to.be();
    });

    it('should have the property modifiedOn (base name: "modifiedOn")', function() {
      // uncomment below and update the code to test the property modifiedOn
      //var instane = new ArtikCloud.DeviceTypeInfo();
      //expect(instance).to.be();
    });

    it('should have the property dtid (base name: "dtid")', function() {
      // uncomment below and update the code to test the property dtid
      //var instane = new ArtikCloud.DeviceTypeInfo();
      //expect(instance).to.be();
    });

    it('should have the property pmin (base name: "pmin")', function() {
      // uncomment below and update the code to test the property pmin
      //var instane = new ArtikCloud.DeviceTypeInfo();
      //expect(instance).to.be();
    });

    it('should have the property taskExpiresAfter (base name: "taskExpiresAfter")', function() {
      // uncomment below and update the code to test the property taskExpiresAfter
      //var instane = new ArtikCloud.DeviceTypeInfo();
      //expect(instance).to.be();
    });

    it('should have the property createdOn (base name: "createdOn")', function() {
      // uncomment below and update the code to test the property createdOn
      //var instane = new ArtikCloud.DeviceTypeInfo();
      //expect(instance).to.be();
    });

  });

}));
