/**
 * ARTIK Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ArtikCloud);
  }
}(this, function(expect, ArtikCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ArtikCloud.DeviceTypePricingTier();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DeviceTypePricingTier', function() {
    it('should create an instance of DeviceTypePricingTier', function() {
      // uncomment below and update the code to test DeviceTypePricingTier
      //var instane = new ArtikCloud.DeviceTypePricingTier();
      //expect(instance).to.be.a(ArtikCloud.DeviceTypePricingTier);
    });

    it('should have the property revenueSharePercent (base name: "revenueSharePercent")', function() {
      // uncomment below and update the code to test the property revenueSharePercent
      //var instane = new ArtikCloud.DeviceTypePricingTier();
      //expect(instance).to.be();
    });

    it('should have the property tiers (base name: "tiers")', function() {
      // uncomment below and update the code to test the property tiers
      //var instane = new ArtikCloud.DeviceTypePricingTier();
      //expect(instance).to.be();
    });

    it('should have the property modifiedOn (base name: "modifiedOn")', function() {
      // uncomment below and update the code to test the property modifiedOn
      //var instane = new ArtikCloud.DeviceTypePricingTier();
      //expect(instance).to.be();
    });

    it('should have the property comments (base name: "comments")', function() {
      // uncomment below and update the code to test the property comments
      //var instane = new ArtikCloud.DeviceTypePricingTier();
      //expect(instance).to.be();
    });

    it('should have the property dtid (base name: "dtid")', function() {
      // uncomment below and update the code to test the property dtid
      //var instane = new ArtikCloud.DeviceTypePricingTier();
      //expect(instance).to.be();
    });

    it('should have the property contactInfo (base name: "contactInfo")', function() {
      // uncomment below and update the code to test the property contactInfo
      //var instane = new ArtikCloud.DeviceTypePricingTier();
      //expect(instance).to.be();
    });

    it('should have the property ptType (base name: "ptType")', function() {
      // uncomment below and update the code to test the property ptType
      //var instane = new ArtikCloud.DeviceTypePricingTier();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instane = new ArtikCloud.DeviceTypePricingTier();
      //expect(instance).to.be();
    });

    it('should have the property createdOn (base name: "createdOn")', function() {
      // uncomment below and update the code to test the property createdOn
      //var instane = new ArtikCloud.DeviceTypePricingTier();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new ArtikCloud.DeviceTypePricingTier();
      //expect(instance).to.be();
    });

  });

}));
