/**
 * ARTIK Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ArtikCloud);
  }
}(this, function(expect, ArtikCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ArtikCloud.ExportRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ExportRequest', function() {
    it('should create an instance of ExportRequest', function() {
      // uncomment below and update the code to test ExportRequest
      //var instane = new ArtikCloud.ExportRequest();
      //expect(instance).to.be.a(ArtikCloud.ExportRequest);
    });

    it('should have the property endDate (base name: "endDate")', function() {
      // uncomment below and update the code to test the property endDate
      //var instane = new ArtikCloud.ExportRequest();
      //expect(instance).to.be();
    });

    it('should have the property format (base name: "format")', function() {
      // uncomment below and update the code to test the property format
      //var instane = new ArtikCloud.ExportRequest();
      //expect(instance).to.be();
    });

    it('should have the property order (base name: "order")', function() {
      // uncomment below and update the code to test the property order
      //var instane = new ArtikCloud.ExportRequest();
      //expect(instance).to.be();
    });

    it('should have the property sdids (base name: "sdids")', function() {
      // uncomment below and update the code to test the property sdids
      //var instane = new ArtikCloud.ExportRequest();
      //expect(instance).to.be();
    });

    it('should have the property sdtids (base name: "sdtids")', function() {
      // uncomment below and update the code to test the property sdtids
      //var instane = new ArtikCloud.ExportRequest();
      //expect(instance).to.be();
    });

    it('should have the property startDate (base name: "startDate")', function() {
      // uncomment below and update the code to test the property startDate
      //var instane = new ArtikCloud.ExportRequest();
      //expect(instance).to.be();
    });

    it('should have the property trialId (base name: "trialId")', function() {
      // uncomment below and update the code to test the property trialId
      //var instane = new ArtikCloud.ExportRequest();
      //expect(instance).to.be();
    });

    it('should have the property uids (base name: "uids")', function() {
      // uncomment below and update the code to test the property uids
      //var instane = new ArtikCloud.ExportRequest();
      //expect(instance).to.be();
    });

  });

}));
