/**
 * ARTIK Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ArtikCloud);
  }
}(this, function(expect, ArtikCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ArtikCloud.TaskRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TaskRequest', function() {
    it('should create an instance of TaskRequest', function() {
      // uncomment below and update the code to test TaskRequest
      //var instane = new ArtikCloud.TaskRequest();
      //expect(instance).to.be.a(ArtikCloud.TaskRequest);
    });

    it('should have the property filter (base name: "filter")', function() {
      // uncomment below and update the code to test the property filter
      //var instane = new ArtikCloud.TaskRequest();
      //expect(instance).to.be();
    });

    it('should have the property taskType (base name: "taskType")', function() {
      // uncomment below and update the code to test the property taskType
      //var instane = new ArtikCloud.TaskRequest();
      //expect(instance).to.be();
    });

    it('should have the property dtid (base name: "dtid")', function() {
      // uncomment below and update the code to test the property dtid
      //var instane = new ArtikCloud.TaskRequest();
      //expect(instance).to.be();
    });

    it('should have the property property (base name: "property")', function() {
      // uncomment below and update the code to test the property property
      //var instane = new ArtikCloud.TaskRequest();
      //expect(instance).to.be();
    });

    it('should have the property dids (base name: "dids")', function() {
      // uncomment below and update the code to test the property dids
      //var instane = new ArtikCloud.TaskRequest();
      //expect(instance).to.be();
    });

    it('should have the property taskParameters (base name: "taskParameters")', function() {
      // uncomment below and update the code to test the property taskParameters
      //var instane = new ArtikCloud.TaskRequest();
      //expect(instance).to.be();
    });

  });

}));
