/**
 * ARTIK Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ArtikCloud);
  }
}(this, function(expect, ArtikCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ArtikCloud.UnregisterDeviceResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UnregisterDeviceResponse', function() {
    it('should create an instance of UnregisterDeviceResponse', function() {
      // uncomment below and update the code to test UnregisterDeviceResponse
      //var instane = new ArtikCloud.UnregisterDeviceResponse();
      //expect(instance).to.be.a(ArtikCloud.UnregisterDeviceResponse);
    });

    it('should have the property certificateInfo (base name: "certificateInfo")', function() {
      // uncomment below and update the code to test the property certificateInfo
      //var instane = new ArtikCloud.UnregisterDeviceResponse();
      //expect(instance).to.be();
    });

    it('should have the property certificateSignature (base name: "certificateSignature")', function() {
      // uncomment below and update the code to test the property certificateSignature
      //var instane = new ArtikCloud.UnregisterDeviceResponse();
      //expect(instance).to.be();
    });

    it('should have the property createdOn (base name: "createdOn")', function() {
      // uncomment below and update the code to test the property createdOn
      //var instane = new ArtikCloud.UnregisterDeviceResponse();
      //expect(instance).to.be();
    });

    it('should have the property dtid (base name: "dtid")', function() {
      // uncomment below and update the code to test the property dtid
      //var instane = new ArtikCloud.UnregisterDeviceResponse();
      //expect(instance).to.be();
    });

    it('should have the property eid (base name: "eid")', function() {
      // uncomment below and update the code to test the property eid
      //var instane = new ArtikCloud.UnregisterDeviceResponse();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new ArtikCloud.UnregisterDeviceResponse();
      //expect(instance).to.be();
    });

    it('should have the property manifestVersion (base name: "manifestVersion")', function() {
      // uncomment below and update the code to test the property manifestVersion
      //var instane = new ArtikCloud.UnregisterDeviceResponse();
      //expect(instance).to.be();
    });

    it('should have the property manifestVersionPolicy (base name: "manifestVersionPolicy")', function() {
      // uncomment below and update the code to test the property manifestVersionPolicy
      //var instane = new ArtikCloud.UnregisterDeviceResponse();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new ArtikCloud.UnregisterDeviceResponse();
      //expect(instance).to.be();
    });

    it('should have the property needProviderAuth (base name: "needProviderAuth")', function() {
      // uncomment below and update the code to test the property needProviderAuth
      //var instane = new ArtikCloud.UnregisterDeviceResponse();
      //expect(instance).to.be();
    });

    it('should have the property uid (base name: "uid")', function() {
      // uncomment below and update the code to test the property uid
      //var instane = new ArtikCloud.UnregisterDeviceResponse();
      //expect(instance).to.be();
    });

  });

}));
