/**
 * ARTIK Cloud API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ArtikCloud);
  }
}(this, function(expect, ArtikCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ArtikCloud.MessagesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MessagesApi', function() {
    describe('getAggregatesHistogram', function() {
      it('should call getAggregatesHistogram successfully', function(done) {
        //uncomment below and update the code to test getAggregatesHistogram
        //instance.getAggregatesHistogram(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFieldPresence', function() {
      it('should call getFieldPresence successfully', function(done) {
        //uncomment below and update the code to test getFieldPresence
        //instance.getFieldPresence(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLastNormalizedMessages', function() {
      it('should call getLastNormalizedMessages successfully', function(done) {
        //uncomment below and update the code to test getLastNormalizedMessages
        //instance.getLastNormalizedMessages(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMessageAggregates', function() {
      it('should call getMessageAggregates successfully', function(done) {
        //uncomment below and update the code to test getMessageAggregates
        //instance.getMessageAggregates(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMessageSnapshots', function() {
      it('should call getMessageSnapshots successfully', function(done) {
        //uncomment below and update the code to test getMessageSnapshots
        //instance.getMessageSnapshots(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNormalizedMessages', function() {
      it('should call getNormalizedMessages successfully', function(done) {
        //uncomment below and update the code to test getNormalizedMessages
        //instance.getNormalizedMessages(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('sendMessageAction', function() {
      it('should call sendMessageAction successfully', function(done) {
        //uncomment below and update the code to test sendMessageAction
        //instance.sendMessageAction(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
