/**
 * ARTIK Cloud API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ArtikCloud);
  }
}(this, function(expect, ArtikCloud) {
  'use strict';

  var propertiesReader = require('properties-reader');
  var properties = propertiesReader('./test/artik.properties');

  var api;

  beforeEach(function() {
    var newClient = new ArtikCloud.ApiClient();

    // Configure OAuth2 access token for authorization: artikcloud_oauth
    var artikcloud_oauth = newClient.authentications['artikcloud_oauth'];
    artikcloud_oauth.accessToken = properties.get("device1.token");

    api = new ArtikCloud.MessagesApi(newClient);
    api.getApiClient
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MessagesApi', function() {
    describe('getAggregatesHistogram', function() {
      it('should call getAggregatesHistogram successfully', function(done) {
        //uncomment below and update the code to test getAggregatesHistogram
        //instance.getAggregatesHistogram(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFieldPresence', function() {
      it('should call getFieldPresence successfully', function(done) {
        //uncomment below and update the code to test getFieldPresence
        //instance.getFieldPresence(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLastNormalizedMessages', function() {
      it('should call getLastNormalizedMessages successfully', function(done) {
        var sdid = properties.get("device1.id");
        api.getLastNormalizedMessages({"sdids": sdid}, function(error, response) {
          if (error) throw error;

          expect(response.size).to.be(1);

          var normalized = response.data[0];

          //var distance = normalized.data['distance'];
          //expect(distance).to.be(850.745);

          var steps = normalized.data['steps'];
          expect(steps).to.be(935);

          done();
        });
      });
    });
    describe('getMessageAggregates', function() {
      it('should call getMessageAggregates successfully', function(done) {
        //uncomment below and update the code to test getMessageAggregates
        //instance.getMessageAggregates(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMessageSnapshots', function() {
      it('should call getMessageSnapshots successfully', function(done) {
        //uncomment below and update the code to test getMessageSnapshots
        //instance.getMessageSnapshots(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNormalizedMessages', function() {
      it('should call getNormalizedMessages successfully', function(done) {
        //uncomment below and update the code to test getNormalizedMessages
        //instance.getNormalizedMessages(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('sendMessage', function() {
      it('should call sendMessage successfully', function(done) {
        var message = new ArtikCloud.Message();
        message.sdid = properties.get("device1.id");
        message.ts = Date.now();
        message.data = {"distance":850.745,"steps":935};

        api.sendMessage(message, function(error, response) {
          if (error) throw error;

          var messageId = response.data.mid;
          var opts = {'mid': messageId};

          api.getNormalizedMessages(opts, function(error2, response2) {
            if (error2) throw error2;

            expect(response2.size).to.be(1);

            var normalized = response2.data[0];
            expect(normalized.mid).to.be(messageId);

            var distance = normalized.data['distance'];
            expect(distance).to.be(850.745);

            var steps = normalized.data['steps'];
            expect(steps).to.be(935);

            done();
          });
        });
      });
    });
    describe('sendActions', function() {
      it('should call sendActions successfully', function(done) {

        var newClient = new ArtikCloud.ApiClient();
        var artikcloud_oauth = newClient.authentications['artikcloud_oauth'];
        artikcloud_oauth.accessToken = properties.get("device4.token");

        var api2 = new ArtikCloud.MessagesApi(newClient);

        var action = new ArtikCloud.Action();
        action.name = "setVolume";
        action.parameters = {"volume": 5};

        var actionArray = new ArtikCloud.ActionArray();
        //actionArray.actions = [];
        //actionArray.actions.push(action);
        actionArray.actions = [ action ];

        var actions = new ArtikCloud.Actions();
        actions.ddid = properties.get("device4.id");
        actions.ts = Date.now();
        actions.data = actionArray;
        actions.type = "action";

        api2.sendActions(actions, function(error, response) {
          console.log(response);
          if (error) throw error;

          var messageId = response.data.mid;
          var opts = {'mid': messageId, 'type': 'action'};

          api2.getNormalizedActions(opts, function(error2, response2) {
            if (error2) throw error2;

            expect(response2.size).to.be(1);

            var normalized = response2.data[0];
            expect(normalized.mid).to.be(messageId);

            var name = normalized.data.actions[0].name;
            expect(name).to.be('setVolume');

            var parameters = normalized.data.actions[0].parameters;
            expect(parameters.volume).to.be(5);

            done();
          });

        });
      });
    });

  });

}));
