/**
 * ARTIK Cloud API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ArtikCloud);
  }
}(this, function(expect, ArtikCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ArtikCloud.MessagesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MessagesApi', function() {
    describe('getAggregatesHistogram', function() {
      it('should call getAggregatesHistogram successfully', function(done) {
        //uncomment below and update the code to test getAggregatesHistogram
        //instance.getAggregatesHistogram(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFieldPresence', function() {
      it('should call getFieldPresence successfully', function(done) {
        //uncomment below and update the code to test getFieldPresence
        //instance.getFieldPresence(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLastNormalizedMessages', function() {
      it('should call getLastNormalizedMessages successfully', function(done) {
        //uncomment below and update the code to test getLastNormalizedMessages
        //instance.getLastNormalizedMessages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMessageAggregates', function() {
      it('should call getMessageAggregates successfully', function(done) {
        //uncomment below and update the code to test getMessageAggregates
        //instance.getMessageAggregates(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMessageSnapshots', function() {
      it('should call getMessageSnapshots successfully', function(done) {
        //uncomment below and update the code to test getMessageSnapshots
        //instance.getMessageSnapshots(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNormalizedActions', function() {
      it('should call getNormalizedActions successfully', function(done) {
        //uncomment below and update the code to test getNormalizedActions
        //instance.getNormalizedActions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNormalizedMessages', function() {
      it('should call getNormalizedMessages successfully', function(done) {
        //uncomment below and update the code to test getNormalizedMessages
        //instance.getNormalizedMessages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('sendActions', function() {
      it('should call sendActions successfully', function(done) {
        //uncomment below and update the code to test sendActions
        //instance.sendActions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('sendMessage', function() {
      it('should call sendMessage successfully', function(done) {
        //uncomment below and update the code to test sendMessage
        //instance.sendMessage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });

  });

})}));
